# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UsageStats Main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UsageStats(object):
    def setupUi(self, UsageStats):
        UsageStats.setObjectName("UsageStats")
        UsageStats.resize(1418, 856)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UsageStats.sizePolicy().hasHeightForWidth())
        UsageStats.setSizePolicy(sizePolicy)
        UsageStats.setMinimumSize(QtCore.QSize(1000, 500))
        UsageStats.setMaximumSize(QtCore.QSize(16777215, 16777215))
        UsageStats.setSizeIncrement(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icon1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UsageStats.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(UsageStats)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(320, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(251, 18))
        self.comboBox.setMaximumSize(QtCore.QSize(1000, 30))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 200))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(500, 200))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setSizeIncrement(QtCore.QSize(-26721, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(170)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(320, 51))
        self.groupBox_3.setMaximumSize(QtCore.QSize(500, 500))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_4.sizePolicy().hasHeightForWidth())
        self.radioButton_4.setSizePolicy(sizePolicy)
        self.radioButton_4.setMinimumSize(QtCore.QSize(90, 30))
        self.radioButton_4.setMaximumSize(QtCore.QSize(70, 16))
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_2.addWidget(self.radioButton_4)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_3.sizePolicy().hasHeightForWidth())
        self.radioButton_3.setSizePolicy(sizePolicy)
        self.radioButton_3.setMinimumSize(QtCore.QSize(120, 30))
        self.radioButton_3.setMaximumSize(QtCore.QSize(93, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
        self.radioButton_2.setSizePolicy(sizePolicy)
        self.radioButton_2.setMinimumSize(QtCore.QSize(150, 30))
        self.radioButton_2.setMaximumSize(QtCore.QSize(104, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 3, 1, 1)
        UsageStats.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(UsageStats)
        self.statusbar.setObjectName("statusbar")
        UsageStats.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(UsageStats)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1418, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        UsageStats.setMenuBar(self.menubar)
        self.actionClose = QtWidgets.QAction(UsageStats)
        self.actionClose.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionClose.setShortcutVisibleInContextMenu(True)
        self.actionClose.setObjectName("actionClose")
        self.actionUsage_Stats = QtWidgets.QAction(UsageStats)
        self.actionUsage_Stats.setObjectName("actionUsage_Stats")
        self.actionResents_Task = QtWidgets.QAction(UsageStats)
        self.actionResents_Task.setObjectName("actionResents_Task")
        self.actionNew_Case_2 = QtWidgets.QAction(UsageStats)
        self.actionNew_Case_2.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionNew_Case_2.setShortcutVisibleInContextMenu(True)
        self.actionNew_Case_2.setObjectName("actionNew_Case_2")
        self.actionUsage_Stats_2 = QtWidgets.QAction(UsageStats)
        self.actionUsage_Stats_2.setObjectName("actionUsage_Stats_2")
        self.actionRecent_Tasks = QtWidgets.QAction(UsageStats)
        self.actionRecent_Tasks.setObjectName("actionRecent_Tasks")
        self.actionUsage_Stats_3 = QtWidgets.QAction(UsageStats)
        self.actionUsage_Stats_3.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionUsage_Stats_3.setShortcutVisibleInContextMenu(True)
        self.actionUsage_Stats_3.setObjectName("actionUsage_Stats_3")
        self.actionResent_Tasks = QtWidgets.QAction(UsageStats)
        self.actionResent_Tasks.setObjectName("actionResent_Tasks")
        self.actionFull_Case_Folder = QtWidgets.QAction(UsageStats)
        self.actionFull_Case_Folder.setShortcutVisibleInContextMenu(True)
        self.actionFull_Case_Folder.setObjectName("actionFull_Case_Folder")
        self.actionOpen_Case = QtWidgets.QAction(UsageStats)
        self.actionOpen_Case.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionOpen_Case.setShortcutVisibleInContextMenu(True)
        self.actionOpen_Case.setObjectName("actionOpen_Case")
        self.actionRead_Me = QtWidgets.QAction(UsageStats)
        self.actionRead_Me.setObjectName("actionRead_Me")
        self.actionAbout = QtWidgets.QAction(UsageStats)
        self.actionAbout.setObjectName("actionAbout")
        self.actionRemove_Case_Folder = QtWidgets.QAction(UsageStats)
        self.actionRemove_Case_Folder.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionRemove_Case_Folder.setObjectName("actionRemove_Case_Folder")
        self.menu.addAction(self.actionNew_Case_2)
        self.menu.addSeparator()
        self.menu.addAction(self.actionOpen_Case)
        self.menu.addSeparator()
        self.menu.addAction(self.actionRemove_Case_Folder)
        self.menu.addSeparator()
        self.menu.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionRead_Me)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(UsageStats)
        self.actionClose.triggered.connect(UsageStats.close)
        QtCore.QMetaObject.connectSlotsByName(UsageStats)

    def retranslateUi(self, UsageStats):
        _translate = QtCore.QCoreApplication.translate
        UsageStats.setWindowTitle(_translate("UsageStats", "Usage Stats\\Recent Task Parser"))
        self.groupBox_2.setTitle(_translate("UsageStats", "Hide Column"))
        self.comboBox.setItemText(0, _translate("UsageStats", "---- Show/Hide Columns ----"))
        self.tableWidget.setSortingEnabled(False)
        self.groupBox_3.setTitle(_translate("UsageStats", "Show/Hide Checked Rows"))
        self.radioButton_4.setText(_translate("UsageStats", "Show All"))
        self.radioButton_3.setText(_translate("UsageStats", "Show Checked"))
        self.radioButton_2.setText(_translate("UsageStats", "Show Unchecked"))
        self.label.setText(_translate("UsageStats", "Case Number:"))
        self.label_2.setText(_translate("UsageStats", "Evidence Item Number:"))
        self.label_3.setText(_translate("UsageStats", "Device Owner:"))
        self.pushButton.setText(_translate("UsageStats", "Create Report"))
        self.pushButton.setShortcut(_translate("UsageStats", "Ctrl+R"))
        self.menu.setTitle(_translate("UsageStats", "File"))
        self.menuHelp.setTitle(_translate("UsageStats", "Help"))
        self.actionClose.setText(_translate("UsageStats", "Close"))
        self.actionClose.setShortcut(_translate("UsageStats", "Ctrl+Q"))
        self.actionUsage_Stats.setText(_translate("UsageStats", "Usage Stats"))
        self.actionResents_Task.setText(_translate("UsageStats", "Resents Task"))
        self.actionNew_Case_2.setText(_translate("UsageStats", "New Case"))
        self.actionNew_Case_2.setShortcut(_translate("UsageStats", "Ctrl+N"))
        self.actionUsage_Stats_2.setText(_translate("UsageStats", "Usage Stats"))
        self.actionRecent_Tasks.setText(_translate("UsageStats", "Recent Tasks"))
        self.actionUsage_Stats_3.setText(_translate("UsageStats", "Individual File"))
        self.actionUsage_Stats_3.setShortcut(_translate("UsageStats", "Ctrl+I"))
        self.actionResent_Tasks.setText(_translate("UsageStats", "Resent Tasks"))
        self.actionFull_Case_Folder.setText(_translate("UsageStats", "Full Case/Evidence Item Folder"))
        self.actionFull_Case_Folder.setShortcut(_translate("UsageStats", "Ctrl+F"))
        self.actionOpen_Case.setText(_translate("UsageStats", "Open Case"))
        self.actionOpen_Case.setShortcut(_translate("UsageStats", "Ctrl+O"))
        self.actionRead_Me.setText(_translate("UsageStats", "Read Me"))
        self.actionAbout.setText(_translate("UsageStats", "About"))
        self.actionRemove_Case_Folder.setText(_translate("UsageStats", "Remove Case Folder"))
        self.actionRemove_Case_Folder.setShortcut(_translate("UsageStats", "Ctrl+D"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UsageStats = QtWidgets.QMainWindow()
    ui = Ui_UsageStats()
    ui.setupUi(UsageStats)
    UsageStats.show()
    sys.exit(app.exec_())

